spring.application.name=ecome.proj
server.port=8181

logging.level.org.springframework=debug
spring.datasource.url=jdbc:h2:mem:telusko
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.defer-datasource-initialization=true
 spring.jpa.defer-datasource-initialization=true
 spring.jpa.open-in-view=false